### ISSUE TITLE
Latest release doesn't work with imports in JupyterLab 3.6.x

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab_rtc#57]
## Description

The latest release of jupyter_server_ydoc has rearranged the internal module structure which breaks how this is imported in JupyterLab 3.6.x here:

https://github.com/jupyterlab/jupyterlab/blob/master/jupyterlab/labapp.py#L15

Could we get a new release of JupyterLab 3.6.x with the right import so we can do end to end testing with the new jupyter_server_ydoc release?

**Comment by SylvainCorlay** [comment]
JupyterLab 3.6.x requires `jupyter_server_ydoc~=0.2.0` which should still work..

If I am not mistaken `jupyter_server_ydoc` 0.3.0 is the version that makes that change, and PR https://github.com/jupyterlab/jupyterlab/pull/13413 should upgrade JupyterLab to use Jupyter_server_ydoc to 0.3.0.

**Comment by fcollonval** [comment]
For JupyterLab 3.6.x the versions have been pinned:

https://github.com/jupyterlab/jupyterlab/blob/3.6.x/setup.cfg#L41-L42.
