### ISSUE TITLE
jupyter-releaser not working

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab_rtc#78]
The npm build command is not run inside the releaser copy but in the code repository.

_Originally posted by @fcollonval in https://github.com/jupyter-server/jupyter_server_ydoc/issues/77#issuecomment-1415954228_

**Comment by blink1073** [comment]
I'm not sure, [`build_npm`](https://github.com/jupyter-server/jupyter_releaser/blob/ca70ff1bfcf87430b341eee825ff7ce95b50783e/jupyter_releaser/cli.py#L494) has the `@use_checkout_dir` decorator, and we should be switching to the checkout [dir](https://github.com/jupyter-server/jupyter_releaser/blob/ca70ff1bfcf87430b341eee825ff7ce95b50783e/jupyter_releaser/cli.py#L45) before running the hooks.

**Comment by hbcarlos** [comment]
fixed in #82
