### ISSUE TITLE
Merge with the `jupyterlab/rtc` repo?

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab_rtc#83]
### Problem

As discussed during the [JupyterLab Weekly Call yesterday](https://github.com/jupyterlab/team-compass/issues/170#issuecomment-1423873392), there are now 2 RTC repositories in the `jupyterlab` organization:

![image](https://user-images.githubusercontent.com/591645/217774719-57f66b54-62b2-4656-af34-42645082923d.png)

### Proposed Solution

Would it make sense to move the content of https://github.com/jupyterlab/jupyterlab_rtc to https://github.com/jupyterlab/rtc?

And keep the previous content in a separate branch so it can still be browsed if needed.

### Additional context

https://github.com/jupyterlab/rtc was meant to be archived at some point: https://github.com/jupyterlab/rtc/issues/136. But maybe it should be the place where development is happening now.

**Comment by fcollonval** [comment]
The [jupyterlab/rtc](https://github.com/jupyterlab/rtc) repository as been merged as branch [automerge](https://github.com/jupyterlab/jupyterlab_rtc/tree/automerge) within this repository.
